services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: athlemetry
    ports:
      - "5432:5432"
    volumes:
      - athlemetry_pgdata:/var/lib/postgresql/data
volumes:
  athlemetry_pgdata:
